// Product data with images and descriptions
const PRODUCTS = {
  juvederm_ultra: {
    id: 'juvederm_ultra',
    name: '乔雅登雅致',
    brand: 'Juvéderm Ultra',
    brandCN: '乔雅登',
    maker: '艾尔建 Allergan (美国)',
    img: 'https://img.alicdn.com/imgextra/i3/2215305604/O1CN01KqZ8Xz1gXrDjLmQ8p_!!2215305604.jpg',
    price: 8800,
    unit: '/支 (0.8ml)',
    type: '中分子玻尿酸',
    tech: 'HYLACROSS™ 交联技术',
    duration: '12-18个月',
    hardness: '中等 (G\'≈50-80Pa)',
    features: ['柔顺自然', '延展性好', '适合浅层修饰'],
    suitable: ['鼻基底填充', '唇部塑形', '浅层皱纹', '眉弓微调', '面部轮廓柔化'],
    desc: '乔雅登雅致采用HYLACROSS™专利交联技术，凝胶质地柔顺细腻，注射后效果自然柔和。中分子量设计使其兼具支撑力与延展性，特别适合面部浅层至中层填充，可实现细腻的轮廓优化，触感真实，无颗粒感。',
    fda: true,
    nmpa: true,
  },
  juvederm_voluma: {
    id: 'juvederm_voluma',
    name: '乔雅登极致',
    brand: 'Juvéderm Voluma',
    brandCN: '乔雅登',
    maker: '艾尔建 Allergan (美国)',
    img: 'https://img.alicdn.com/imgextra/i4/2215305604/O1CN01vNqGPF1gXrDoSHp3X_!!2215305604.jpg',
    price: 12800,
    unit: '/支 (1.0ml)',
    type: '大分子玻尿酸',
    tech: 'VYCROSS™ 交联技术',
    duration: '18-24个月',
    hardness: '较硬 (G\'≈200-300Pa)',
    features: ['强支撑力', '立体塑形', '持久稳定'],
    suitable: ['下巴塑形', '鼻部增高', '颧骨填充', '面部轮廓重塑', '深层支撑'],
    desc: '乔雅登极致采用VYCROSS™新一代交联技术，大分子量赋予卓越的支撑力和塑形能力。独特的内聚性设计使其在深层注射后稳定不位移，可实现立体的骨性结构重塑效果，是面部轮廓塑形的首选产品。',
    fda: true,
    nmpa: true,
  },
  restylane: {
    id: 'restylane',
    name: '瑞蓝2号',
    brand: 'Restylane',
    brandCN: '瑞蓝',
    maker: '高德美 Galderma (瑞典)',
    img: 'https://img.alicdn.com/imgextra/i2/2215305604/O1CN01mKQp5F1gXrDnC3QvD_!!2215305604.jpg',
    price: 6800,
    unit: '/支 (1.0ml)',
    type: '中分子玻尿酸',
    tech: 'NASHA™ 非动物源性交联技术',
    duration: '6-12个月',
    hardness: '中等 (G\'≈60-100Pa)',
    features: ['颗粒感强', '支撑稳固', '不易扩散'],
    suitable: ['苹果肌填充', '鼻部塑形', '法令纹填充', '面部中度皱纹', '唇部丰盈'],
    desc: '瑞蓝2号采用NASHA™专利技术，独特的颗粒状凝胶结构提供稳固支撑，不易扩散移位。作为全球首款非动物源性透明质酸填充剂，安全可靠，临床应用超过25年，是中度面部填充的经典选择。',
    fda: true,
    nmpa: true,
  },
  elravie: {
    id: 'elravie',
    name: '艾莉薇',
    brand: 'Elravie',
    brandCN: '艾莉薇',
    maker: '韩士生科 Huons (韩国)',
    img: 'https://img.alicdn.com/imgextra/i1/2215305604/O1CN01LqMqYD1gXrDoZRLVR_!!2215305604.jpg',
    price: 5800,
    unit: '/支 (1.0ml)',
    type: '中分子玻尿酸',
    tech: 'MCL™ 多层交联技术',
    duration: '9-12个月',
    hardness: '中等偏柔 (G\'≈40-70Pa)',
    features: ['弹性优异', '自然融合', '性价比高'],
    suitable: ['太阳穴填充', '面部动态区域', '浅层细纹', '面部基础填充', '初次填充'],
    desc: '艾莉薇采用MCL™多层交联技术，凝胶弹性出色，与面部组织融合度高。特别适合面部动态区域填充，表情自然不僵硬。作为韩国销量领先的玻尿酸品牌，性价比优越，是入门级面部填充的优质选择。',
    fda: false,
    nmpa: true,
  },
  jouvence: {
    id: 'jouvence',
    name: '姣兰',
    brand: 'Jouvence',
    brandCN: '姣兰',
    maker: '法国生科 (法国)',
    img: 'https://img.alicdn.com/imgextra/i3/2215305604/O1CN01wRfQHN1gXrDnBwKqT_!!2215305604.jpg',
    price: 4800,
    unit: '/支 (1.0ml)',
    type: '小分子玻尿酸',
    tech: '单相交联技术',
    duration: '6-9个月',
    hardness: '柔软 (G\'≈20-40Pa)',
    features: ['细腻柔软', '适合浅层', '过渡自然'],
    suitable: ['法令纹填充', '浅层细纹', '面部微调', '唇部细纹', '泪沟填充'],
    desc: '姣兰采用单相交联技术，凝胶质地细腻柔软，特别适合面部浅层细纹填充和微调。注射后过渡自然，无明显边界感，是精细部位修饰的理想选择。价格亲民，适合首次尝试或小面积填充。',
    fda: false,
    nmpa: true,
  },
};

// Map material keys to product IDs
const MAT_TO_PRODUCT = {
  '乔雅登雅致': 'juvederm_ultra',
  '乔雅登极致': 'juvederm_voluma',
  '瑞蓝2号': 'restylane',
  '艾莉薇': 'elravie',
  '姣兰': 'jouvence',
};
